language: python
python:
    - "2.7"
    - "3.5"
    - "nightly"
before_install:
    - nvm install node
    - npm install -g gulp
    - npm install -g bower
install:
    - pip install -r requirements.txt
    - npm install
    - bower install
    - gulp build-app
script: 
    - python manage.py db init
    - python manage.py db upgrade
cache:
    - pip
    - npm
notifications:
    slack:
        secure: a+PPcrZIHbTEECj701sRLCM3nL0S3CfoLH/gq0vsZ8VKXFsR544LVD4qra7mKVx/azC3q5dFBr4gwJyqjDg/VXI1Zz4cXfGLOYkyl8lzzU8veBPwFX2EGHFS2iaaEIwcKX5PJFDfo15agufm+fmZvoXPlOHku8zT+eBqw0Q/vrsKZTgh9DZmsZok0gsqmP1InK4Y1aQ4pk0JXOjiFJUZWteZcumR2GPiEMsIZ9MKaXeNeegqnLhzM43+KeR+1HUwADtywh8Sx6c4ELh14r0kWLgdK52WqgNs++6/Z4GlP+bFOk31vBiqe09Egow6cdDifyMQXj0BNiktC8XAxoVhcEyCPcFcWSPYIEEevOP/QOTyYHsBIPJZIUpeRdBv4q945OAm83E1yUDgyLc5PybwKdUnjk+38rcjItPUW1phsK8YxwG5nG2OWaIJMqD2/Fz3byUJBb8YtrvW2Y7E35L7H1iXqSiYcmuxr6aPtO4rUV6RA8nlHlb2SJjqx06c4fdoGpIhIMhc0dHMIdayIQb8PO2ioBhfXmCt7AmZudqGMByivF+sw1FhPAGwsAUB++ALed1La0UD8q23DU2JgbrWf1DxqRESPFhahK1UeOKNtK41rqcG8zSYCTOCVYj8NxS3xV57gSW3pnHI3yV5jBmIWk1QGPTTvGVc=
